name: Deploy Vite ke GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Mengambil file repository
        uses: actions/checkout@v7

      - name: Memasang Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Memasang dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Menyiapkan GitHub Pages
        uses: actions/configure-pages@v6

      - name: Mengunggah hasil build
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

      - name: Menerbitkan website
        id: deployment
        uses: actions/deploy-pages@v5
